name: Deploy Power BI Reports to Workspace

on:
  push:
    branches:
      - main  # Trigger this workflow when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use a Linux runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up PowerShell to run Power BI related scripts
      - name: Set up PowerShell
        uses: microsoft/setup-powershell@v1
        with:
          version: '7.x'

      # Step 3: Authenticate to Power BI using GitHub Secrets
      - name: Authenticate to Power BI
        run: |
          $clientId = "c15b611c-d346-4053-82c9-9dc4dce58b08"
          $clientSecret = "rvA8Q~ekdJve89BS1F2liPyQOiJHJ2VwbIbsrb8M"
          $tenantId = "e4e34038-ea1f-4882-b6e8-ccd776459ca0"
          
          # Perform authentication using the above credentials
          # Example: PowerShell script to authenticate
          $token = Get-PowerBIAccessToken -ClientId $clientId -ClientSecret $clientSecret -TenantId $tenantId
          Write-Host "Authentication Successful"
        
      # Step 4: Deploy the Power BI reports to the workspace
      - name: Power BI Workspace Deploy
        # uses: nathangiusti/Power-BI-Workspace-Deploy@v1.3
        with:
          tenant_id: 'e4e34038-ea1f-4882-b6e8-ccd776459ca0'
          files: 'Power-BI/test_workbook.pbix'  # Files to deploy
          separator: ','  # Separator for multiple files
